### ISSUE TITLE
please fix patch file

### ISSUE THREAD

**Issue by wongsyrone** [aa65535/openwrt-shadowvpn#13]
In clowwindy/ShadowVPN@efe6a479221e6e9273f0f2644f7d8380de6074c0
```patch
EXTRA_DIST = \
autogen.sh \
README.md \
- LICENSE
+ COPYING
SUBDIRS = src samples
```
this causes Hunk fail

**Comment by aa65535** [comment]
https://github.com/aa65535/openwrt-shadowvpn/blob/master/Makefile#L14-L16

This commit of ShadowVPN not yet released, next version will update it.
