### ISSUE TITLE
stopping service problems

### ISSUE THREAD

**Issue by alviezhang** [aa65535/openwrt-shadowvpn#16]
When I want to restart vpn daemon, it often takes a long time, then print follow message:

    Fri Jun 26 18:32:42 2015 timed out when stopping pid 1415
    Fri Jun 26 18:32:42 2015 can not stop daemon

Some times I get `can not stop, not running`, but actually the service is running.

via: `OpenWrt Barrier Breaker 14.07 / LuCI Trunk (0.12+svn-r10530)`

`opkg list-installed | grep shadowvpn -i`

    ShadowVPN - 0.1.6-1
    luci-app-shadowvpn - 1.3.2-1

**Comment by aa65535** [comment]
Cannot reproduce, the process may be hung up.
