### ISSUE TITLE
为什么要取消系统对服务的控制，另设一个选项？

### ISSUE THREAD

**Issue by Arnie97** [aa65535/openwrt-shadowvpn#28]
按照目前的设计，无论在系统中设定`shadowvpn`为Enabled还是Disabled都不起任何作用，开机时是否启动只取决于Luci App设置界面中的第一个选项。
既然OpenWrt自身已经提供了启用/禁用服务的方法，为什么要加一个选项，并且让系统自带功能失效呢？

**Comment by Arnie97** [comment]
据我观察，OpenWrt-dist中大部分Luci App都设计了这个选项，但是我没有测试其他包是否也会无视系统的服务管理。

**Comment by aa65535** [comment]
一个是服务是否自动启动的开关，
一个是服务是否启动的开关。

**Comment by Arnie97** [comment]
@aa65535 我还是不太理解。即使我在系统选项里设为Disabled，只要luci-app-shadowvpn里勾上Enabled，结果还是会自动启动啊？

**Comment by aa65535** [comment]
系统里那个是指是否在路由器开机启动后启动shadowvpn，并不能阻止在设置页面手动启动。
@aa65535 我还是不太理解。即使我在系统选项里设为Disabled，只要luci-app-shadowvpn里勾上Enabled，结果还是会自动启动啊？

---

**Comment by Arnie97** [comment]
@aa65535 手动Start/Stop当然不会受系统的Disable限制，我现在讨论的只是自动启动。我认为有问题的地方在于，只要luci-app-shadowvpn里处于Enabled状态，即使系统里设为Disabled，shadowvpn都会**自动**启动。问题出在/etc/init.d/shadowvpn上。
